@startuml
title : Cas ou quand on est sur la case piege est Faux
participant Clavier
Clavier -> Main : Apuyer sur une touche dirrectionelle
activate Clavier
activate Main
Main -> Personnage : action(direction)
activate Personnage
Personnage --> Main
deactivate Personnage
Main -> Labyrinthe : deplacerPersonnage(Personnage)
activate Labyrinthe
Labyrinthe -> DeplacementClavier : deplacer(Personnage,Labyrinthe)
activate DeplacementClavier
DeplacementClavier --> Labyrinthe
deactivate DeplacementClavier
Labyrinthe -> Labyrinthe : repercution
activate Labyrinthe
Labyrinthe -> Labyrinthe : estSurCasePiege
activate Labyrinthe
Labyrinthe -> Coordonnees : etreSurMemeCase
activate Coordonnees
Coordonnees --> Labyrinthe : false
deactivate Coordonnees
deactivate Personnage
Labyrinthe --> Labyrinthe
Labyrinthe --> Labyrinthe
deactivate Labyrinthe
Labyrinthe --> Main
deactivate Labyrinthe
return
@enduml