@startuml
participant Clavier
activate Clavier
Clavier -> Main : Apuyer sur une touche dirrectionelle
activate Main
Main -> Personnage : action(direction)
activate Personnage
Personnage --> Main
deactivate Personnage
Main -> Labyrinthe : deplacerPersonnage(Personnage)
activate Labyrinthe
Labyrinthe -> DeplacementClavier : deplacer(Personnage,Labyrinthe)
activate DeplacementClavier
DeplacementClavier --> Labyrinthe
deactivate DeplacementClavier
Labyrinthe -> Labyrinthe : repercution
activate Labyrinthe
Labyrinthe -> Labyrinthe : estSurCasePiege
activate Labyrinthe
Labyrinthe -> Coordonnees : etreSurMemeCase
activate Coordonnees
Coordonnees --> Labyrinthe : true
deactivate Coordonnees
Labyrinthe -> Personnage : perdrePv(1)
activate Personnage
Personnage --> Labyrinthe
deactivate Personnage
Labyrinthe --> Labyrinthe
deactivate Labyrinthe


Labyrinthe --> Labyrinthe
deactivate Labyrinthe
Labyrinthe --> Main
deactivate Labyrinthe
return
@enduml