@startuml
activate LabyJeu
title : Attaque d'un monstre cas faux
LabyJeu -> Labyrinthe : deplacerPersonnage(Monstre)
activate Labyrinthe
Labyrinthe -> TypeDeplacement : deplacer(Monstre,Labyrinte)
activate TypeDeplacement
TypeDeplacement --> Labyrinthe
deactivate TypeDeplacement
Labyrinthe -> Labyrinthe : repercution
activate Labyrinthe

Labyrinthe -> Personnage : estAutour(Personnage)
activate Personnage
Personnage --> Labyrinthe : false
deactivate Personnage
Labyrinthe --> Labyrinthe

deactivate Labyrinthe
return
note across
Lorsqu'un monstre ce deplace la methode etreautour test si autour de lui il y a un personnage et si c'est le cas on appel la methode attaquer 
end note
@enduml