@startuml
activate LabyJeu
LabyJeu -> Labyrinthe : deplacerPersonnage(Monstre)
activate Labyrinthe
Labyrinthe -> TypeDeplacement : deplacer(Monstre,Labyrinte)
activate TypeDeplacement
TypeDeplacement --> Labyrinthe
deactivate TypeDeplacement
Labyrinthe -> Labyrinthe : repercution
activate Labyrinthe

Labyrinthe -> Personnage : estAutour(Personnage)
activate Personnage
Personnage --> Labyrinthe : true
deactivate Personnage
Labyrinthe -> Personnage : attaquer(Personnage)
activate Personnage
Personnage -> TypeAttaque : attaquer(Monstre attaquant,Personnage victime)
activate TypeAttaque
TypeAttaque -> Personnage : PerdrePv(1)
activate Personnage
Personnage --> TypeAttaque
deactivate Personnage
TypeAttaque --> Personnage
deactivate TypeAttaque
Personnage --> Labyrinthe
deactivate Personnage
Labyrinthe --> Labyrinthe

deactivate Labyrinthe
return
@enduml