@startuml
participant LabyJeu
title : Personnage qui attaque cas Faux
participant Personnage
participant Monstre
LabyJeu -> Personnage : appuie sur espace
activate Personnage
loop Pour tout les monstres "victime"
    Personnage -> Monstre : attaquer(victime,AttaqueAlentour)

    activate Monstre
    Monstre -> "AttaqueAlentour" : attaquer(Personnage attaquant, victime)
    activate "AttaqueAlentour"
    "AttaqueAlentour" -> Personnage : estAutour(victime)
    Personnage --> "AttaqueAlentour" : false
    "AttaqueAlentour" --> Monstre : void
    deactivate "AttaqueAlentour"
    Monstre --> Personnage : void
    deactivate Monstre
end
Personnage -> "Labyrinthe" : majEtatMonstre()
activate "Labyrinthe"
"Labyrinthe" --> "Labyrinthe" : majEtatMonstre()

"Labyrinthe" --> "Personnage" : void
deactivate "Labyrinthe"
Personnage --> LabyJeu : void
deactivate Personnage
note across
Lorsqu'un personnage veut attaquer l'utilisateur appuie sur espace et si il y a un monstre autour alors il prend des degats et on met a jour l'état du monstre
end note
@enduml

