@startuml
actor User
participant Main
participant Labyrinthe
participant Monstre
participant Random

User -> Main: update()
activate Main
Main -> Labyrinthe: deplacerMonstre()
activate Labyrinthe
Labyrinthe -> Monstre: getPosition()
activate Monstre
Monstre -> Monstre: choisirDirectionAleatoire()
Monstre -> Random: randomDirection()
activate Random
Random -> Monstre: return direction
deactivate Random
Monstre -> Labyrinthe: getSuivant(x, y, direction)
Monstre -> Labyrinthe: getMur(nouvellePosition)
Labyrinthe -> Monstre: return mur
alt Si nouvellePosition n'est pas un mur
    Monstre -> Monstre: setPosition(nouvellePosition)
end
deactivate Monstre
deactivate Labyrinthe
deactivate Main
@enduml
