@startuml
actor User
participant Main
participant Labyrinthe
participant Perso
participant Monstre

User -> Main: deplacerPerso(action)
activate Main
Main -> Labyrinthe: deplacerPerso(action)
activate Labyrinthe
Labyrinthe -> Perso: getSuivant(x, y, action)
activate Perso
Perso -> Labyrinthe: return nouvellePosition
deactivate Perso
Labyrinthe -> Monstre: getPosition()
activate Monstre
Monstre -> Labyrinthe: return positionMonstre
deactivate Monstre
alt Si nouvellePosition != positionMonstre
    Labyrinthe -> Perso: setPosition(nouvellePosition)
end
deactivate Labyrinthe
deactivate Main
@enduml
