@startuml
actor User
participant MainLaby
participant MoteurJeu
participant LabyJeu
participant LabyDessin
participant Canvas

User -> MainLaby: main()
activate MainLaby
MainLaby -> MoteurJeu: setTaille(width, height)
MainLaby -> MoteurJeu: setFPS(fps)
MainLaby -> MoteurJeu: launch(LabyJeu, LabyDessin)
activate MoteurJeu
MoteurJeu -> LabyJeu: update()
activate LabyJeu
LabyJeu -> LabyDessin: dessinerJeu(jeu, canvas)
activate LabyDessin
LabyDessin -> Canvas: getGraphicsContext2D()
LabyDessin -> Canvas: fillOval(monstre.getX(), monstre.getY(), size, size)
deactivate LabyDessin
deactivate LabyJeu
deactivate MoteurJeu
deactivate MainLaby
@enduml
