@startuml
participant Actor
title : Creation de monstre
Actor -> Labyrinthe : creerMonstres
activate Labyrinthe
Labyrinthe -> Labyrinthe : personnagePresent
activate Labyrinthe
Labyrinthe -> Personnage : etrePresent
activate Personnage
Personnage --> Labyrinthe:boolean
deactivate Personnage
deactivate Personnage
Labyrinthe --> Labyrinthe
deactivate Labyrinthe
create Monstre
Labyrinthe -> Monstre : new
activate Monstre
create Personnage
Monstre -> Personnage : new
activate Personnage
Personnage --> Monstre: Monstre
deactivate Personnage
Monstre --> Labyrinthe:Monstre
deactivate Monstre
note across
Maitenant quand on créé un personnage il passe par le constructeur de la classe Personnage
end note
@enduml