@startuml
participant Actor
Actor -> Labyrinthe : creerMonstres
activate Labyrinthe
Labyrinthe -> Labyrinthe : personnagePresent
activate Labyrinthe
Labyrinthe -> Personnage : etrePresent
activate Personnage
Personnage --> Labyrinthe:boolean
deactivate Personnage
deactivate Personnage
Labyrinthe --> Labyrinthe
deactivate Labyrinthe
create Monstre
Labyrinthe -> Monstre : new
activate Monstre
create Personnage
Monstre -> Personnage : new
activate Personnage
Personnage --> Monstre: Monstre
deactivate Personnage
Monstre --> Labyrinthe:Monstre
deactivate Monstre
return
@enduml