@startuml
title : Creation d'une amulette
Labyrinthe -> Labyrinthe: Labyrinthe()
activate Labyrinthe
alt Si la lettre est a
    Labyrinthe-> Amulette: Amulette(x,y)
    activate Amulette
    Amulette -->Labyrinthe:Amulette
    deactivate Amulette
else
end
deactivate Labyrinthe
note across
Lorsque dans le fichier on lit a on creer l'objet amulette a cette position
end note

@enduml