@startuml
participant Main
title : Personnage recupere amulette cas true
Main -> Labyrinthe : deplacerPersonnage(Perso,DeplacementClavier)
activate Labyrinthe
Labyrinthe -> TypeDeplacement : deplacer(labyrinthe,Perso)
activate TypeDeplacement
TypeDeplacement --> Labyrinthe
deactivate TypeDeplacement
Labyrinthe -> Labyrinthe : repercution()
activate Labyrinthe
Labyrinthe -> Labyrinthe : recupererAmulette()
activate Labyrinthe

Labyrinthe -> Amulette : etreSurMemeCase(Perso)
activate Amulette
Amulette --> Labyrinthe : true
deactivate Amulette
Labyrinthe -> Personnage : setPossedeAmulette(true);
activate Personnage
Personnage --> Labyrinthe
deactivate Personnage
Labyrinthe --> Labyrinthe
deactivate Labyrinthe
Labyrinthe --> Labyrinthe
deactivate Labyrinthe
return
note across
Lorsque le personnage est placer sur l'amulette il la recupere et son argument passe a vrai et l'amulette devient null
end note
@enduml