@startuml
participant Actor
title : Personnage qui essaye de recuperer Amulette
Actor -> Labyrinthe : deplacerPersonnage(Perso,DeplacementClavier)
activate Labyrinthe
Labyrinthe -> TypeDeplacement : deplacer()
activate TypeDeplacement
TypeDeplacement --> Labyrinthe
deactivate TypeDeplacement
Labyrinthe -> Labyrinthe : repercution
activate Labyrinthe
Labyrinthe -> Labyrinthe : recupererAmulette
activate Labyrinthe

Labyrinthe -> Amulette : etreSurMemeCase(Perso)
activate Amulette
Amulette --> Labyrinthe : false
deactivate Amulette
Labyrinthe --> Labyrinthe
deactivate Labyrinthe
Labyrinthe --> Labyrinthe
deactivate Labyrinthe
return
note across
Lorsque le personnage est placer sur l'amulette il la recupere et son argument passe a vrai et l'amulette devient null
end note
@enduml