@startuml
Participant Main
title : Cas ou il a pas encore gagner(manque amulette)
participant LabyJeu
participant Labyrinthe
participant Personnage
activate Main

Main -> LabyJeu : estFini()
activate LabyJeu
LabyJeu -> Labyrinthe : getDepart()
activate Labyrinthe
Labyrinthe --> LabyJeu : depart
deactivate Labyrinthe

LabyJeu -> Personnage : etreSurMemeCase(depart.getX(), depart.getY())
activate Personnage
Personnage --> LabyJeu : true
deactivate Personnage
LabyJeu -> Personnage : getPossedeAmulette()
activate Personnage
Personnage --> LabyJeu : false
deactivate Personnage
LabyJeu --> LabyJeu : void

LabyJeu --> Main : void
deactivate LabyJeu
note across
Lorsque le personnage n'a plus de pv il perd, lorsque il possede l'amulette et qu'il est sur la case de depart qui est genere lors de la creation du personnage car il s'agit de la meme case
end note
@enduml