@startuml
Labyrinthe -> Labyrinthe: Labyrinthe()
activate Labyrinthe
alt Si la lettre est a
    Labyrinthe-> Amulette: Amulette(x,y)
    activate Amulette
    Amulette -->Labyrinthe:Amulette
    deactivate Amulette
else
end
deactivate Labyrinthe

@enduml