@startuml
participant Actor
Actor -> Labyrinthe : repercution
activate Labyrinthe
Labyrinthe -> Labyrinthe : estSurCasePiege
activate Labyrinthe
Labyrinthe -> Coordonnees : etreSurMemeCase
activate Coordonnees
Coordonnees --> Labyrinthe
deactivate Coordonnees
Labyrinthe -> Personnage : perdrePv
activate Personnage
Personnage -> Personnage : estMort
activate Personnage
Personnage --> Personnage
deactivate Personnage
Personnage --> Labyrinthe
deactivate Personnage
Labyrinthe --> Labyrinthe
deactivate Labyrinthe
Labyrinthe -> Personnage : estAutour
activate Personnage
Personnage --> Labyrinthe
deactivate Personnage
Labyrinthe -> Personnage : attaquer
activate Personnage
Personnage -> Personnage : estMort
activate Personnage
Personnage --> Personnage
deactivate Personnage
Personnage -> TypeAttaque : attaquer
activate TypeAttaque
TypeAttaque --> Personnage
deactivate TypeAttaque
Personnage --> Labyrinthe
deactivate Personnage
Labyrinthe -> Labyrinthe : recupererAmulette
activate Labyrinthe
Labyrinthe -> Coordonnees : etreSurMemeCase
activate Coordonnees
Coordonnees --> Labyrinthe
deactivate Coordonnees
Labyrinthe --> Labyrinthe
deactivate Labyrinthe
return
@enduml